### ISSUE TITLE
[Bug]: Empty body in HttpTransporter::requestObject ($response->getBody()->getContents()) when using Guzzle client with Middleware::log()

### ISSUE THREAD

**Issue by root-phpdev** [mozex/anthropic-php#4]
### Description

When using the Guzzle client and middleware to log requests/responses in the \Anthropic\Transporters\HttpTransporter::requestObject() method, when calling $response->getBody()->getContents() the result is an empty string. This is a well known old issue https://github.com/guzzle/guzzle/issues/1582

Perhaps to solve the problem it is worth using cast to string or calling the __toString() method

`$contents = (string) $response->getBody();`

### Steps To Reproduce

```php
$stack = HandlerStack::create();

$stack->push(Middleware::log(
    $this->logger,
    new MessageFormatter('{hostname} {req_header_User-Agent} - [{date_common_log}] "{method} {uri} HTTP/{version}" {code} {res_header_Content-Type} {res_header_Content-Length} {res_body}')
));

$httpClient = new \GuzzleHttp\Client([
    'handler' => $stack,
]);

$client = Anthropic::factory()
    ->withApiKey($yourApiKey)
    ->withHttpClient($httpClient)
    ->make();
```

### Anthropic PHP Client Version

v.1.0.1

### PHP Version

8.1.20

**Comment by mozex** [comment]
Can you add a failing test for this issue? I waited for openai-php/client#432 to get an answer and see how they would resolve it because someone had already reported this problem on `openai-php/client` and the changes were made, but they were reversed, so I want to know why before making the changes here.

**Comment by mozex** [comment]
I'm closing this for now because there has been no response; feel free to reopen if you want to follow up on fixing this issue.
