### ISSUE TITLE
[Bug]: Tools use response missing from Anthropic\Responses\Messages\CreateResponseContent

### ISSUE THREAD

**Issue by SDLarose** [mozex/anthropic-php#5]
### Description

When using function calling, the response from the `client->messages()->create` doesn't contain the associated data:
- id
- name
- input

The response content is being parsed out by the Anthropic\Responses\Messages\CreateResponseContent::from(), since it's only applying the type and text parameters.

### Steps To Reproduce

Use any function calling via the messages()->create() and observe the response.

We should be seeing CreateResponseContent with the following parameters:
- type: 'tool_use'
- id: 'id of the tool response',
- name: 'name of the function to use'
- input: 'parameters to pass to the function'

### Anthropic PHP Client Version

v1.0.2

### PHP Version

8.3.10

### Notes

Currently, I've bypassed the issue by overwriting the Anthropic\Responses\Messages\CreateResponseContent::from() in order to add missing fields. Obviously, this isn't viable for future releases.

```php
public static function from(array $attributes): self
{
    return new self(
        type: $attributes['type'],
        text: $attributes['text'] ?? null,
        id: $attributes['id'] ?? null,
        name: $attributes['name'] ?? null,
        input: $attributes['input'] ?? null,
    );
}
```

**Comment by mozex** [comment]
Currently, tool use is not supported. I am working on it, and It will be available by the next release

**Comment by SDLarose** [comment]
Do you have a timeline for the next release @mozex ?
Depending on it, I might have to convert my app to use the API directly via the URL.

**Comment by mozex** [comment]
I will try to finish it by end of the week.

**Comment by mozex** [comment]
Tool use support has been added to the [1.1.0](https://github.com/mozex/anthropic-php/releases/tag/1.1.0) version. Please update your dependencies and let me know if you have any issues.
